platform :ios, '15.0'

target 'iosApp' do
  use_frameworks!

  # Shared KMM Framework
  pod 'shared', :path => '../shared'
  
  # Firebase
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  
  # Google Maps (opcional)
  # pod 'GoogleMaps'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['CODE_SIGN_STYLE'] = 'Automatic'
      config.build_settings['PROVISIONING_PROFILE'] = ''
      config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      
      # Fix para Xcode 16.4
      if config.name == 'Debug'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
      end
    end
  end
end

