platform :ios, '16.0'

target 'iosApp' do
  use_frameworks!

  # Shared KMM Framework
  pod 'shared', :path => '../shared'

  # Firebase
  pod 'Firebase/Auth',      '~> 11.0'
  pod 'Firebase/Firestore', '~> 11.0'
  pod 'Firebase/Messaging', '~> 11.0'

end

post_install do |installer|
  # Fix para projetos gerados (abseil, gRPC-C++ precisam de C++20 no Xcode 16.4)
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++20'
        config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
      end
    end
  end

  # Fix para pods normais
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      config.build_settings['CODE_SIGN_STYLE'] = 'Automatic'
      config.build_settings['PROVISIONING_PROFILE'] = ''
      config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
      config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++20'
      config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
      config.build_settings['ENABLE_PREVIEWS'] = 'NO'
    end
  end
end
