name: iosApp
options:
  bundleIdPrefix: br.com.afilaxy
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15"

settings:
  SWIFT_VERSION: "5.9"
  DEVELOPMENT_TEAM: "$(DEVELOPMENT_TEAM)"

targets:
  iosApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: iosApp
    resources:
      - path: iosApp/iosApp/GoogleService-Info.plist
      - path: iosApp/iosApp/LaunchScreen.storyboard
      - path: iosApp/Assets.xcassets
        optional: true
    info:
      path: iosApp/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.afilaxy.app
        INFOPLIST_FILE: iosApp/Info.plist
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "15.0"
        DEVELOPMENT_TEAM: "$(DEVELOPMENT_TEAM)"
        CODE_SIGN_STYLE: Automatic
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  iosApp:
    build:
      targets:
        iosApp: all
    run:
      config: Debug
    archive:
      config: Release
